### ISSUE TITLE
Case ID Extractor for Tamil Nadu (TN)

### ISSUE THREAD

**Issue by TathagataChakraborti** [IBM/covid19-india-data#27]
The [Tamil Nadu health bulletins](https://stopcorona.tn.gov.in/daily-bulletin/) provide case-level details of each COVID patient, like this:

```
Death Case No. 34725

A 55 Years old Female from Kancheepuram having COVID-19 RTPCR
Positivity on 04.08.2021 admitted on 04.08.2021 at 10.02 PM in a private
medical college and hospital, Kancheepuram with Complaints of Fever,
Cough and Difficulty in Breathing for 2 days died on 22.08.2021 at 11.57
PM due to COVID-19 Pneumonia.
```

This is not tabular data and the structure of this description varies a bit but this would be a wealth of information if it can be extracted accurately and made available in a structured form.

## Proposal

```yaml
CaseInfo:
  id: int
  age: int
  gender: str
  location: str
  commorbidity: str
  test: 
    date: str
    type: str
  symptoms: 
    details: str
    days: int
  admission:
    location: str
    date: str
    time: str
  death: 
    cause: str
    date: str
    time: str
```
